POST http://localhost:8080/api/pmlogs
Content-Type: application/json

    {
    "sensorId": "sensorA",
    "latitude": "52.43545465",
    "longitude": "22.44445454",
    "pm2P5": 32.53,
    "timestamp": "2022-12-28 01:04:07.000"
}